import{a as b,S as v,i}from"./assets/vendor-CVWx-W0A.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();async function f(s,o=1){return(await b.get("https://pixabay.com/api/",{params:{key:"56333257-5e55ad218ba23a27bfc212fa1",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function q(){m.innerHTML=""}function p(s){const o=s.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div>
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",o),S.refresh()}function g(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}function w(){y.classList.remove("is-hidden")}function l(){y.classList.add("is-hidden")}const u=document.querySelector(".form"),M=document.querySelector(".load-more");let n=1,c="";u.addEventListener("submit",async s=>{if(s.preventDefault(),c=u.elements["search-text"].value.trim(),!!c){n=1,q(),l(),g();try{const o=await f(c,n),{hits:t,totalHits:a}=o;if(t.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}p(t);const e=Math.ceil(a/15);if(n>=e){l(),i.info({message:"We're sorry, but you've reached the end of search results."});return}w()}catch{i.error({message:"Something went wrong. Try again!"})}finally{L()}}});M.addEventListener("click",async()=>{n+=1,g(),l();try{const s=await f(c,n),{hits:o,totalHits:t}=s;p(o);const a=document.querySelector(".gallery-item");if(a){const r=a.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}const e=Math.ceil(t/15);if(n>=e){l(),i.info({message:"We're sorry, but you've reached the end of search results."});return}w()}catch{i.error({message:"Something went wrong. Try again!"})}finally{L()}});
//# sourceMappingURL=index.js.map
